language: node_js
node_js:
  - "12"
  - "10"
  - "8"
os:
  - linux
  - osx
  - windows
before_script:
script:
  - if [ ${TRAVIS_EVENT_TYPE} = "cron" ]; then
        npm run publish-nightly;
    else
        npm test;
    fi
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
