language: node_js
node_js:
  - "14"
  - "12"
  - "10"
os:
  - linux
  - osx
  - windows
before_script:
  - if [ ${TRAVIS_OS_NAME} = "linux" ]; then
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
        chmod +x ./cc-test-reporter;
        ./cc-test-reporter before-build;
    fi
script:
  - npm test
after_script:
  - if [ ${TRAVIS_OS_NAME} = "linux" ]; then
        ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT;
    fi
